import { Complaint, RouteItem } from './types';

export const MOCK_ROUTES: RouteItem[] = [
  { id: 'RT-01', code: 'Tuyến 01', name: 'Bến Thành - Bến xe Chợ Lớn' },
  { id: 'RT-02', code: 'Tuyến 03', name: 'Bến Thành - Thạnh Lộc' },
  { id: 'RT-03', code: 'Tuyến 08', name: 'Bến xe Quận 8 - ĐH Quốc Gia' },
  { id: 'RT-04', code: 'Tuyến 19', name: 'Bến Thành - Khu chế xuất Linh Trung' },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'CMP-2026-001',
    passengerName: 'Phạm Quốc Huy',
    passengerEmail: 'passenger@bus.com',
    passengerPhone: '0934567890',
    routeId: 'RT-01',
    tripDate: '2026-09-26',
    category: 'DELAY',
    subject: 'Xe buýt trễ hơn 25 phút so với biểu đồ giờ',
    description: 'Chuyến xe dự kiến đón tại trạm Hàng Xanh lúc 07:15 sáng nhưng đến 07:42 mới tới, khiến tôi bị trễ giờ làm việc quan trọng tại trung tâm quận 1.',
    createdAt: '2026-09-26 08:30:00',
    status: 'RESOLVED',
    adminResponse: 'Đã kiểm tra dữ liệu GPS. Chuyến xe gặp sự cố ùn ứ nghiêm trọng tại giao lộ Điện Biên Phủ do sự cố giao thông. Đã nhắc nhở điều độ điều chỉnh tần suất giờ cao điểm.',
    processedBy: 'Trần Minh Đức (Quản lý)',
    processedAt: '2026-09-26 14:10:00',
  },
  {
    id: 'CMP-2026-002',
    passengerName: 'Đặng Thảo Vy',
    passengerEmail: 'thaovy.dang@gmail.com',
    passengerPhone: '0918765432',
    routeId: 'RT-03',
    tripDate: '2026-09-27',
    category: 'ATTITUDE',
    subject: 'Thái độ phục vụ của nhân viên soát vé chưa nhã nhặn',
    description: 'Nhân viên soát vé trên chuyến xe 51B-291.88 có lời nói gắt gỏng khi sinh viên xuất trình thẻ sinh viên điện tử qua ứng dụng trên điện thoại.',
    createdAt: '2026-09-27 10:15:00',
    status: 'PROCESSING',
    adminResponse: 'Đã chuyển thông tin tới đội trưởng Đội Vận Tải 2 để yêu cầu lái phụ xe giải trình trong chiều nay.',
    processedBy: 'Trần Minh Đức (Quản lý)',
    processedAt: '2026-09-27 11:30:00',
  },
  {
    id: 'CMP-2026-003',
    passengerName: 'Lê Hoàng Nam',
    passengerEmail: 'hoangnam.le@yahoo.com',
    passengerPhone: '0988112233',
    routeId: 'RT-02',
    tripDate: '2026-09-27',
    category: 'VEHICLE_QUALITY',
    subject: 'Hệ thống điều hòa trên xe không hoạt động tốt',
    description: 'Khoang xe rất nóng và có mùi dầu nồng nặc trong suốt hành trình từ Bệnh viện Từ Dũ về Công viên Phú Lâm lúc 12h trưa.',
    createdAt: '2026-09-27 13:40:00',
    status: 'PENDING',
  },
  {
    id: 'CMP-2026-004',
    passengerName: 'Vũ Thị Mai',
    passengerEmail: 'maivu88@gmail.com',
    passengerPhone: '0903445566',
    routeId: 'RT-04',
    tripDate: '2026-09-28',
    category: 'OVERCHARGING',
    subject: 'Thu thêm phụ phí hành lý không có trong bảng niêm yết',
    description: 'Tôi mang theo 1 vali xách tay cỡ nhỏ theo đúng tiêu chuẩn hành lý miễn cước nhưng phụ xe yêu cầu nộp thêm 10.000đ vé phụ.',
    createdAt: '2026-09-28 09:00:00',
    status: 'PENDING',
  },
  {
    id: 'CMP-2026-005',
    passengerName: 'Nguyễn Tấn Đạt',
    passengerEmail: 'tandat.nguyen@gmail.com',
    passengerPhone: '0977223344',
    routeId: 'RT-01',
    tripDate: '2026-09-28',
    category: 'SAFETY',
    subject: 'Lái xe chạy quá tốc độ và tấp lề nguy hiểm',
    description: 'Tại đoạn đường Võ Thị Sáu xe buýt chạy vượt đèn vàng và phanh gấp khiến nhiều hành khách lớn tuổi bị ngã dúi dụi.',
    createdAt: '2026-09-28 16:20:00',
    status: 'PROCESSING',
    adminResponse: 'Đã trích xuất camera giám sát hành trình trên xe để lập biên bản xử phạt lái xe vi phạm quy tắc an toàn.',
    processedBy: 'Lê Thành Long (Điều hành)',
    processedAt: '2026-09-28 17:00:00',
  },
];
