// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBusTicketing.Api.Data;

#nullable disable

namespace SmartBusTicketing.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetResource")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Username", "ActionType", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("HoldExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PassengerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VoucherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.HasIndex("VoucherId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Bus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("buses", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.BusLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("TripId");

                    b.ToTable("bus_locations", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.BusRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Fare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<int>("PassengerTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PassengerTypeId");

                    b.HasIndex("RouteId");

                    b.ToTable("fares", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<long>("PassengerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProcessedBy")
                        .HasColumnType("bigint");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long?>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("RouteId");

                    b.HasIndex("TripId");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.FeedbackHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ChangedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("FeedbackId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("FeedbackId");

                    b.ToTable("feedback_history", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ReportedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ResolvedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("TripId");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.MonthlyPass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PassengerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("PreviousPassId")
                        .HasColumnType("bigint");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("PassengerTypeId");

                    b.HasIndex("PreviousPassId");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.ToTable("monthly_passes", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TripId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.PassengerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("passenger_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "STANDARD",
                            DiscountPercent = 0m,
                            Name = "Hành khách thường"
                        },
                        new
                        {
                            Id = 2,
                            Code = "STUDENT",
                            DiscountPercent = 50m,
                            Name = "Học sinh / Sinh viên"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ELDERLY",
                            DiscountPercent = 50m,
                            Name = "Người cao tuổi"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WORKER",
                            DiscountPercent = 20m,
                            Name = "Người đi làm (vé tháng)"
                        });
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.PassengerVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PassengerTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PassengerTypeId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("passenger_verifications", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("MonthlyPassId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProviderTxnId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("MonthlyPassId");

                    b.HasIndex("ProviderTxnId")
                        .IsUnique();

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_target", "(`BookingId` IS NOT NULL AND `MonthlyPassId` IS NULL) OR (`BookingId` IS NULL AND `MonthlyPassId` IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Refund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long?>("ChangeRequestId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ProcessedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ProcessedBy");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.RouteStop", b =>
                {
                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<long>("StopId")
                        .HasColumnType("bigint");

                    b.Property<int>("MinutesFromStart")
                        .HasColumnType("int");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "StopId");

                    b.HasIndex("StopId");

                    b.HasIndex("RouteId", "StopOrder")
                        .IsUnique();

                    b.ToTable("route_stops", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("FirstDeparture")
                        .HasColumnType("time(6)");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("LastDeparture")
                        .HasColumnType("time(6)");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SeatCol")
                        .HasColumnType("int");

                    b.Property<int>("SeatRow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId", "SeatCode")
                        .IsUnique();

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Stop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveSeatKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("(CASE WHEN `Status` IN ('Held','Valid','Used') THEN CONCAT(`TripId`, '-', `SeatId`) END)", true);

                    b.Property<long>("AlightStopId")
                        .HasColumnType("bigint");

                    b.Property<long>("BoardStopId")
                        .HasColumnType("bigint");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSeatKey")
                        .IsUnique();

                    b.HasIndex("AlightStopId");

                    b.HasIndex("BoardStopId");

                    b.HasIndex("BookingId");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("SeatId");

                    b.HasIndex("TripId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TicketChangeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("NewSeatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NewTripId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ProcessedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NewSeatId");

                    b.HasIndex("NewTripId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_change_requests", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TicketScan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MonthlyPassId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ScannedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyPassId");

                    b.HasIndex("ScannedBy");

                    b.HasIndex("TicketId");

                    b.HasIndex("TripId");

                    b.ToTable("ticket_scans", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BusId")
                        .HasColumnType("bigint");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("BusId", "DepartureAt")
                        .IsUnique();

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TripStaff", b =>
                {
                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TripId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("trip_staff", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.AuditLog", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Account")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Booking", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Voucher", "Voucher")
                        .WithMany("Bookings")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Passenger");

                    b.Navigation("Trip");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.BusLocation", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Bus", "Bus")
                        .WithMany("Locations")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany("Locations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Fare", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.PassengerType", "PassengerType")
                        .WithMany("Fares")
                        .HasForeignKey("PassengerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.BusRoute", "BusRoute")
                        .WithMany("Fares")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("PassengerType");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Feedback", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusRoute");

                    b.Navigation("Passenger");

                    b.Navigation("Processor");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.FeedbackHistory", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Changer")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Feedback", "Feedback")
                        .WithMany("History")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Changer");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Incident", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany("Incidents")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("Resolver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Invoice", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Payment", "Payment")
                        .WithOne("Invoice")
                        .HasForeignKey("SmartBusTicketing.Api.Models.Invoice", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.MonthlyPass", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Passenger")
                        .WithMany("MonthlyPasses")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.PassengerType", "PassengerType")
                        .WithMany("MonthlyPasses")
                        .HasForeignKey("PassengerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.MonthlyPass", "PreviousPass")
                        .WithMany()
                        .HasForeignKey("PreviousPassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusRoute");

                    b.Navigation("Passenger");

                    b.Navigation("PassengerType");

                    b.Navigation("PreviousPass");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Notification", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Incident", "Incident")
                        .WithMany("Notifications")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Incident");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.PassengerVerification", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Account")
                        .WithMany("PassengerVerifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.PassengerType", "PassengerType")
                        .WithMany("PassengerVerifications")
                        .HasForeignKey("PassengerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("PassengerType");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Payment", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartBusTicketing.Api.Models.MonthlyPass", "MonthlyPass")
                        .WithMany("Payments")
                        .HasForeignKey("MonthlyPassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("MonthlyPass");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Refund", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.TicketChangeRequest", "ChangeRequest")
                        .WithMany("Refunds")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangeRequest");

                    b.Navigation("Payment");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.RouteStop", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.BusRoute", "BusRoute")
                        .WithMany("RouteStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Stop", "Stop")
                        .WithMany("RouteStops")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Schedule", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.BusRoute", "BusRoute")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Seat", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Bus", "Bus")
                        .WithMany("Seats")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Ticket", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Stop", "AlightStop")
                        .WithMany()
                        .HasForeignKey("AlightStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Stop", "BoardStop")
                        .WithMany()
                        .HasForeignKey("BoardStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlightStop");

                    b.Navigation("BoardStop");

                    b.Navigation("Booking");

                    b.Navigation("Seat");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TicketChangeRequest", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Seat", "NewSeat")
                        .WithMany()
                        .HasForeignKey("NewSeatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "NewTrip")
                        .WithMany()
                        .HasForeignKey("NewTripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Ticket", "Ticket")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewSeat");

                    b.Navigation("NewTrip");

                    b.Navigation("Processor");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TicketScan", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.MonthlyPass", "MonthlyPass")
                        .WithMany("Scans")
                        .HasForeignKey("MonthlyPassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Scanner")
                        .WithMany()
                        .HasForeignKey("ScannedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Ticket", "Ticket")
                        .WithMany("Scans")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonthlyPass");

                    b.Navigation("Scanner");

                    b.Navigation("Ticket");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Trip", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBusTicketing.Api.Models.BusRoute", "BusRoute")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Schedule", "Schedule")
                        .WithMany("Trips")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bus");

                    b.Navigation("BusRoute");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TripStaff", b =>
                {
                    b.HasOne("SmartBusTicketing.Api.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBusTicketing.Api.Models.Trip", "Trip")
                        .WithMany("TripStaff")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Account", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bookings");

                    b.Navigation("MonthlyPasses");

                    b.Navigation("PassengerVerifications");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Bus", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Seats");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.BusRoute", b =>
                {
                    b.Navigation("Fares");

                    b.Navigation("RouteStops");

                    b.Navigation("Schedules");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Feedback", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Incident", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.MonthlyPass", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.PassengerType", b =>
                {
                    b.Navigation("Fares");

                    b.Navigation("MonthlyPasses");

                    b.Navigation("PassengerVerifications");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Payment", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Schedule", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Stop", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Ticket", b =>
                {
                    b.Navigation("ChangeRequests");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.TicketChangeRequest", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Incidents");

                    b.Navigation("Locations");

                    b.Navigation("TripStaff");
                });

            modelBuilder.Entity("SmartBusTicketing.Api.Models.Voucher", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
